# Generated by Django 3.0.1 on 2020-04-08 15:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_ticket_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volunteering',
            unique_together={('user', 'ticket')},
        ),
    ]
