# Generated by Django 3.0.3 on 2020-04-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20200408_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='owner',
        ),
    ]
