# Generated by Django 3.0.3 on 2020-04-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20200411_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='title',
        ),
    ]
