# Generated by Django 3.0.3 on 2020-04-12 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20200411_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='zip_code',
            field=models.CharField(default='08271', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{5}(?:[-\\s]\\d{4})?$')], verbose_name='Codi Postal'),
            preserve_default=False,
        ),
    ]
